package taos

// message type
const (
	TSDB_MSG_TYPE_REG          = 1
	TSDB_MSG_TYPE_REG_RSP      = 2
	TSDB_MSG_TYPE_SUBMIT       = 3
	TSDB_MSG_TYPE_SUBMIT_RSP   = 4
	TSDB_MSG_TYPE_NWCHANGE     = 5
	TSDB_MSG_TYPE_NWCHANGE_RSP = 6
	TSDB_MSG_TYPE_DELIVER      = 7
	TSDB_MSG_TYPE_DELIVER_RSP  = 8

	TSDB_MSG_TYPE_CREATE         = 9
	TSDB_MSG_TYPE_CREATE_RSP     = 10
	TSDB_MSG_TYPE_REMOVE         = 11
	TSDB_MSG_TYPE_REMOVE_RSP     = 12
	TSDB_MSG_TYPE_VPEERS         = 13
	TSDB_MSG_TYPE_VPEERS_RSP     = 14
	TSDB_MSG_TYPE_FREE_VNODE     = 15
	TSDB_MSG_TYPE_FREE_VNODE_RSP = 16
	TSDB_MSG_TYPE_VPEER_CFG      = 17
	TSDB_MSG_TYPE_VPEER_CFG_RSP  = 18
	TSDB_MSG_TYPE_METER_CFG      = 19
	TSDB_MSG_TYPE_METER_CFG_RSP  = 20

	TSDB_MSG_TYPE_VPEER_FWD     = 21
	TSDB_MSG_TYPE_VPEER_FWD_RSP = 22
	TSDB_MSG_TYPE_SYNC          = 23
	TSDB_MSG_TYPE_SYNC_RSP      = 24

	TSDB_MSG_TYPE_INSERT       = 25
	TSDB_MSG_TYPE_INSERT_RSP   = 26
	TSDB_MSG_TYPE_QUERY        = 27
	TSDB_MSG_TYPE_QUERY_RSP    = 28
	TSDB_MSG_TYPE_RETRIEVE     = 29
	TSDB_MSG_TYPE_RETRIEVE_RSP = 30

	TSDB_MSG_TYPE_CONNECT          = 31
	TSDB_MSG_TYPE_CONNECT_RSP      = 32
	TSDB_MSG_TYPE_CREATE_ACCT      = 33
	TSDB_MSG_TYPE_CREATE_ACCT_RSP  = 34
	TSDB_MSG_TYPE_CREATE_USER      = 35
	TSDB_MSG_TYPE_CREATE_USER_RSP  = 36
	TSDB_MSG_TYPE_DROP_ACCT        = 37
	TSDB_MSG_TYPE_DROP_ACCT_RSP    = 38
	TSDB_MSG_TYPE_DROP_USER        = 39
	TSDB_MSG_TYPE_DROP_USER_RSP    = 40
	TSDB_MSG_TYPE_ALTER_USER       = 41
	TSDB_MSG_TYPE_ALTER_USER_RSP   = 42
	TSDB_MSG_TYPE_CREATE_MNODE     = 43
	TSDB_MSG_TYPE_CREATE_MNODE_RSP = 44
	TSDB_MSG_TYPE_DROP_MNODE       = 45
	TSDB_MSG_TYPE_DROP_MNODE_RSP   = 46
	TSDB_MSG_TYPE_CREATE_PNODE     = 47
	TSDB_MSG_TYPE_CREATE_PNODE_RSP = 48
	TSDB_MSG_TYPE_DROP_PNODE       = 49
	TSDB_MSG_TYPE_DROP_PNODE_RSP   = 50
	TSDB_MSG_TYPE_CREATE_DB        = 51
	TSDB_MSG_TYPE_CREATE_DB_RSP    = 52
	TSDB_MSG_TYPE_DROP_DB          = 53
	TSDB_MSG_TYPE_DROP_DB_RSP      = 54
	TSDB_MSG_TYPE_USE_DB           = 55
	TSDB_MSG_TYPE_USE_DB_RSP       = 56
	TSDB_MSG_TYPE_CREATE_TABLE     = 57
	TSDB_MSG_TYPE_CREATE_TABLE_RSP = 58

	TSDB_MSG_TYPE_DROP_TABLE      = 59
	TSDB_MSG_TYPE_DROP_TABLE_RSP  = 60
	TSDB_MSG_TYPE_METERINFO       = 61
	TSDB_MSG_TYPE_METERINFO_RSP   = 62
	TSDB_MSG_TYPE_METRIC_META     = 63
	TSDB_MSG_TYPE_METRIC_META_RSP = 64
	TSDB_MSG_TYPE_SHOW            = 65
	TSDB_MSG_TYPE_SHOW_RSP        = 66

	TSDB_MSG_TYPE_FORWARD     = 67
	TSDB_MSG_TYPE_FORWARD_RSP = 68

	TSDB_MSG_TYPE_CFG_PNODE     = 69
	TSDB_MSG_TYPE_CFG_PNODE_RSP = 70
	TSDB_MSG_TYPE_CFG_MNODE     = 71
	TSDB_MSG_TYPE_CFG_MNODE_RSP = 72

	TSDB_MSG_TYPE_KILL_QUERY          = 73
	TSDB_MSG_TYPE_KILL_QUERY_RSP      = 74
	TSDB_MSG_TYPE_KILL_STREAM         = 75
	TSDB_MSG_TYPE_KILL_STREAM_RSP     = 76
	TSDB_MSG_TYPE_KILL_CONNECTION     = 77
	TSDB_MSG_TYPE_KILL_CONNECTION_RSP = 78

	TSDB_MSG_TYPE_ALTER_STREAM     = 79
	TSDB_MSG_TYPE_ALTER_STREAM_RSP = 80
	TSDB_MSG_TYPE_ALTER_TABLE      = 81
	TSDB_MSG_TYPE_ALTER_TABLE_RSP  = 82
	TSDB_MSG_TYPE_ALTER_DB         = 83
	TSDB_MSG_TYPE_ALTER_DB_RSP     = 84

	TSDB_MSG_TYPE_MULTI_METERINFO     = 85
	TSDB_MSG_TYPE_MULTI_METERINFO_RSP = 86

	TSDB_MSG_TYPE_HEARTBEAT     = 91
	TSDB_MSG_TYPE_HEARTBEAT_RSP = 92
	TSDB_MSG_TYPE_STATUS        = 93
	TSDB_MSG_TYPE_STATUS_RSP    = 94
	TSDB_MSG_TYPE_GRANT         = 95
	TSDB_MSG_TYPE_GRANT_RSP     = 96

	TSDB_MSG_TYPE_ALTER_ACCT     = 97
	TSDB_MSG_TYPE_ALTER_ACCT_RSP = 98

	TSDB_MSG_TYPE_MAX = 101
)
