package taos

import (
	"errors"
	"fmt"
)

const (
	TSDB_CODE_SUCCESS            = 0
	TSDB_CODE_ACTION_IN_PROGRESS = 1

	TSDB_CODE_LAST_SESSION_NOT_FINISHED = 5
	TSDB_CODE_INVALID_SESSION_ID        = 6
	TSDB_CODE_INVALID_TRAN_ID           = 7
	TSDB_CODE_INVALID_MSG_TYPE          = 8
	TSDB_CODE_ALREADY_PROCESSED         = 9
	TSDB_CODE_AUTH_FAILURE              = 10
	TSDB_CODE_WRONG_MSG_SIZE            = 11
	TSDB_CODE_UNEXPECTED_RESPONSE       = 12
	TSDB_CODE_INVALID_RESPONSE_TYPE     = 13
	TSDB_CODE_NO_RESOURCE               = 14
	TSDB_CODE_INVALID_TIME_STAMP        = 15
	TSDB_CODE_MISMATCHED_METER_ID       = 16
	TSDB_CODE_ACTION_TRANS_NOT_FINISHED = 17
	TSDB_CODE_ACTION_NOT_ONLINE         = 18
	TSDB_CODE_ACTION_SEND_FAILD         = 19
	TSDB_CODE_NOT_ACTIVE_SESSION        = 20
	TSDB_CODE_INVALID_VNODE_ID          = 21
	TSDB_CODE_APP_ERROR                 = 22
	TSDB_CODE_INVALID_IE                = 23
	TSDB_CODE_INVALID_VALUE             = 24
	TSDB_CODE_REDIRECT                  = 25
	TSDB_CODE_ALREADY_THERE             = 26
	TSDB_CODE_INVALID_METER_ID          = 27
	TSDB_CODE_INVALID_SQL               = 28
	TSDB_CODE_NETWORK_UNAVAIL           = 29
	TSDB_CODE_INVALID_MSG_LEN           = 30
	TSDB_CODE_INVALID_DB                = 31
	TSDB_CODE_INVALID_TABLE             = 32
	TSDB_CODE_DB_ALREADY_EXIST          = 33
	TSDB_CODE_TABLE_ALREADY_EXIST       = 34
	TSDB_CODE_INVALID_USER              = 35
	TSDB_CODE_INVALID_ACCT              = 36
	TSDB_CODE_INVALID_PASS              = 37
	TSDB_CODE_DB_NOT_SELECTED           = 38
	TSDB_CODE_MEMORY_CORRUPTED          = 39
	TSDB_CODE_USER_ALREADY_EXIST        = 40
	TSDB_CODE_NO_RIGHTS                 = 41
	TSDB_CODE_DISCONNECTED              = 42
	TSDB_CODE_NO_MASTER                 = 43
	TSDB_CODE_NOT_CONFIGURED            = 44
	TSDB_CODE_INVALID_OPTION            = 45
	TSDB_CODE_NODE_OFFLINE              = 46
	TSDB_CODE_SYNC_REQUIRED             = 47
	TSDB_CODE_NO_ENOUGH_DNODES          = 48
	TSDB_CODE_UNSYNCED                  = 49
	TSDB_CODE_TOO_SLOW                  = 50
	TSDB_CODE_OTHERS                    = 51
	TSDB_CODE_NO_REMOVE_MASTER          = 52
	TSDB_CODE_WRONG_SCHEMA              = 53
	TSDB_CODE_NOT_ACTIVE_VNODE          = 54
	TSDB_CODE_TOO_MANY_USERS            = 55
	TSDB_CODE_TOO_MANY_DATABSES         = 56
	TSDB_CODE_TOO_MANY_TABLES           = 57
	TSDB_CODE_TOO_MANY_DNODES           = 58
	TSDB_CODE_TOO_MANY_ACCTS            = 59
	TSDB_CODE_ACCT_ALREADY_EXIST        = 60
	TSDB_CODE_DNODE_ALREADY_EXIST       = 61
	TSDB_CODE_SDB_ERROR                 = 62
	TSDB_CODE_METRICMETA_EXPIRED        = 63 // local cached metric-meta expired causes error in metric query
	TSDB_CODE_NOT_READY                 = 64 // peer is not ready to process data
	TSDB_CODE_MAX_SESSIONS              = 65 // too many sessions
	TSDB_CODE_MAX_CONNECTIONS           = 66 // too many connections
	TSDB_CODE_SESSION_ALREADY_EXIST     = 67
	TSDB_CODE_NO_QSUMMARY               = 68
	TSDB_CODE_SERV_OUT_OF_MEMORY        = 69
	TSDB_CODE_INVALID_QHANDLE           = 70
	TSDB_CODE_RELATED_TABLES_EXIST      = 71
	TSDB_CODE_MONITOR_DB_FORBEIDDEN     = 72
	TSDB_CODE_VG_COMMITLOG_INIT_FAILED  = 73
	TSDB_CODE_VG_INIT_FAILED            = 74
	TSDB_CODE_DATA_ALREADY_IMPORTED     = 75
	TSDB_CODE_OPS_NOT_SUPPORT           = 76
	TSDB_CODE_INVALID_QUERY_ID          = 77
	TSDB_CODE_INVALID_STREAM_ID         = 78
	TSDB_CODE_INVALID_CONNECTION        = 79
	TSDB_CODE_ACTION_NOT_BALANCED       = 80
	TSDB_CODE_CLI_OUT_OF_MEMORY         = 81
	TSDB_CODE_DATA_OVERFLOW             = 82
	TSDB_CODE_QUERY_CANCELLED           = 83
	TSDB_CODE_GRANT_TIMESERIES_LIMITED  = 84
	TSDB_CODE_GRANT_EXPIRED             = 85
	TSDB_CODE_CLI_NO_DISKSPACE          = 86
	TSDB_CODE_FILE_CORRUPTED            = 87
	TSDB_CODE_INVALID_CLIENT_VERSION    = 88
	TSDB_CODE_INVALID_ACCT_PARAMETER    = 89
	TSDB_CODE_NOT_ENOUGH_TIME_SERIES    = 90
	TSDB_CODE_NO_WRITE_ACCESS           = 91
	TSDB_CODE_NO_READ_ACCESS            = 92
	TSDB_CODE_GRANT_DB_LIMITED          = 93
	TSDB_CODE_GRANT_USER_LIMITED        = 94
	TSDB_CODE_GRANT_CONN_LIMITED        = 95
	TSDB_CODE_GRANT_STREAM_LIMITED      = 96
	TSDB_CODE_GRANT_SPEED_LIMITED       = 97
	TSDB_CODE_GRANT_STORAGE_LIMITED     = 98
	TSDB_CODE_GRANT_QUERYTIME_LIMITED   = 99
	TSDB_CODE_GRANT_ACCT_LIMITED        = 100
	TSDB_CODE_GRANT_DNODE_LIMITED       = 101
	TSDB_CODE_GRANT_CPU_LIMITED         = 102
	TSDB_CODE_SESSION_NOT_READY         = 103 // table NOT in ready state
	TSDB_CODE_BATCH_SIZE_TOO_BIG        = 104
	TSDB_CODE_TIMESTAMP_OUT_OF_RANGE    = 105
	TSDB_CODE_INVALID_QUERY_MSG         = 106 // failed to validate the sql expression msg by vnode
	TSDB_CODE_CACHE_BLOCK_TS_DISORDERED = 107 // time stamp in cache block is disordered
	TSDB_CODE_FILE_BLOCK_TS_DISORDERED  = 108 // time stamp in file block is disordered
	TSDB_CODE_INVALID_COMMIT_LOG        = 109 // commit log init failed
	TSDB_CODE_SERV_NO_DISKSPACE         = 110
	TSDB_CODE_NOT_SUPER_TABLE           = 111 // operation only available for super table
	TSDB_CODE_DUPLICATE_TAGS            = 112 // tags value for join not unique
	TSDB_CODE_INVALID_SUBMIT_MSG        = 113
	TSDB_CODE_NOT_ACTIVE_TABLE          = 114
	TSDB_CODE_INVALID_TABLE_ID          = 115
	TSDB_CODE_INVALID_VNODE_STATUS      = 116
	TSDB_CODE_FAILED_TO_LOCK_RESOURCES  = 117
	TSDB_CODE_TABLE_ID_MISMATCH         = 118
	TSDB_CODE_QUERY_CACHE_ERASED        = 119

	TSDB_CODE_MAX_ERROR_CODE = 120
)

func GetErrorStr(errorCode int) error {
	if errorCode > 120 || errorCode < 1 {
		return fmt.Errorf("unknow error:%d", errorCode)
	}
	return errors.New(tsError[errorCode])
}
